name: flutter_qrcode_plugin
description: A new Flutter project.
version: 1.0.0+1
environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  assets:
  - assets/

  fonts:
  - family: Roboto
    fonts:
    - asset: assets/fonts/Roboto-Regular.ttf
  - family: MaterialIcons
    fonts:
    - asset: assets/fonts/MaterialIcons-Regular.ttf
